config/routes.rb
Rails.application.routes.draw do
  # 例外
  # get '*not_found', to: 'application#routing_error'
  # post '*not_found', to: 'application#routing_error'
  # match '*path', to: 'application#render_404', via: :all if Rails.env.development?

  namespace :admin do
    resources :users
  end
  root 'tasks#index'
  resources :tasks
  resources :labels
  get '/login', to: 'user_sessions#new'
  post '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'
  get '*path', controller: 'application', action: 'render_404'
  # どのpathにも該当しなければerrorを変えす
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  validates :name, presence: true, length: { in: 1..100 }
  has_many :task_labels, dependent: :destroy
  has_many :tasks, through: :task_labels
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :task_labels, dependent: :destroy
  has_many :labels, through: :task_labels
  validates :name, presence: true, uniqueness: {case_sensitive: true}
  # ユニーク制約は一応貼っておく
  # TODO: DB上でユニークが設定出来てるか不明瞭
  scope :recent, -> { order(created_at: :desc) }
  enum status: %i[waiting working done]
  enum priority: %i[not_yet small medium large]

  #TODO: tasks/indexのjoinをscopeに切り出す

end

app/models/task_label.rb
class TaskLabel < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :least_one_admin
  has_secure_password
  has_many :tasks, dependent: :destroy
  validates :name, presence: true, uniqueness: {case_sensitive: true}
  validates :email, presence: true, uniqueness: true
  enum role: %i[normal admin]

  private

  def least_one_admin
    throw(:abort) if User.admin.count == 1
    # TODO: 下記のようなメッセージ出したいが出せてない、毎回countするのもいかがなものか。
    # flash.now[:danger] = "管理者が最後の一人の場合は削除できません"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_admin_user

  def index
    @q = User.page(params[:page]).ransack(params[:q])
    @users = @q.result
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to admin_users_path, success: "ユーザー「#{@user.name}を作成しました」"
    else
      flash.now[:danger] = "ユーザーの登録に失敗しました。"
      render :new
    end
  end

  def edit
  end

  def show
    @q = @user.tasks.page(params[:page]).per(10).ransack(params[:q])
    @tasks = @q.result
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, success: 'ユーザーを更新しました'
    else
      flash.now[:danger] = 'ユーザーを更新できませんでした'
      render :edit
    end
  end

  def destroy
    @user.destroy!
    redirect_to admin_users_path, success: 'ユーザーを削除しました'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :role)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :login_required
  helper_method :current_user
  add_flash_types :success, :info, :warning, :danger, :notice

  rescue_from Exception, with: :render_500
  if Rails.env.production?
    rescue_from ActiveRecord::RecordNotFound, with: :render_404
    rescue_from ActionController::RoutingError, with: :render_404
  end

  def render_404
    render 'error/404', status: :not_found, layout: false, content_type: 'text/html'
  end

  private

  def render_500
    render 'error/500', status: :internal_server_error, layout: false, content_type: 'text/html'
  end

  private

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path, danger: 'ログインして下さい' unless current_user
  end

  def require_admin_user
    redirect_to root_path, warning: '管理者権限が有りません' unless current_user.admin?
    # 今後管理者の他に属性が増えればレイアウトファイルを分けるべきだが、今回は一般と管理者なので同じコントローラで処理する
  end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_labels, only: %i[show edit update destroy]
  before_action :require_admin_user

  def index
    @labels = Label.all.page(params[:page])
  end

  def new
    @label = Label.new
  end

  def create
    @label = Label.new(labal_params)
    if @label.save
      redirect_to labels_path, success: "ラベル「#{@label.name}」を登録しました。"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @label.update(labal_params)
      redirect_to labels_path(@label), success: "ラベル「#{@label.name}」を更新しました"
    else
      flash.now[:danger] = "ラベルの更新に失敗しました。"
      render :edit
    end
  end

  def destroy
    @label.destroy!
    redirect_to labels_path, danger: 'ラベルを削除しました'
  end

  private

  def set_labels
    @label = Label.find(params[:id])
  end

  def labal_params
    params.require(:label).permit(:name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @q = current_user.tasks.page(params[:page]).per(10).ransack(params[:q])
    @tasks = @q.result
    @tasks = @tasks.joins(:labels).where(labels: { id: params[:label_id] }) if params[:label_id].present?
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    # buildはnewのalias、紐付けた時はbuildにするのが慣習らしい
    if @task.save
      redirect_to tasks_path, success: "タスク「#{@task.name}」を登録しました。"
    else
      flash.now[:danger] = "タスクの登録に失敗しました。"
      render :new
    end

  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to task_path(@task), success: "タスク「#{@task.name}」を更新しました。"
    else
      flash.now[:danger] = "タスクの更新に失敗しました。"
      render :edit
    end
  end

  def destroy
    @task.destroy! # 例外にするべきか悩んだ
    redirect_to tasks_path, danger: 'タスクを削除しました'
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :limit, :status, :priority, {label_ids: []})
  end

  def set_task
    @task = current_user.tasks.find(params[:id])
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :login_required
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user&.authenticate(session_params[:password])
      # レシーバーが nil のときだけはメソッドが呼び出されないで nil を返す
      session[:user_id] = user.id
      redirect_to root_path, success: 'ログインしました。'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to login_path, success: 'ログアウトしました'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/_form.html.slim
= form_with model: [:admin, user], local: true do |f|
  = render 'shared/error_messages', object: f.object
  .form-group
    = f.label :email
    = f.email_field :email, class: 'form-control'
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.label :password
      = f.password_field :password, class: 'form-control'
    .form-group
      = f.label :role
      = f.select :role, User.roles_i18n.invert, {}, class: 'form-control'
    / html系のオプションだけ設定したい場合は、第3引数に空ハッシュを渡し、第4引数にhtml系のオプションを設定する
    = f.submit class: 'btn btn-primary'

app/views/admin/users/_tasks.html.slim
.container.mb-5.pt-2
  .row
    h2 タスク一覧
    .col-md-12
      = render 'shared/task_search_form', search_url: tasks_path, q: @q
    .col-md-12
      .m-3
      table.table.table-hover
        thead.thead-default
          tr
            th= Task.human_attribute_name(:name)
            th= Task.human_attribute_name(:description)
            th= sort_link(@q, :created_at, default_order: :desc)
            th= sort_link(@q, :limit)
            th= sort_link(@q, :priority)
            th= Task.human_attribute_name(:status)
        tbody
          - @tasks.each do |task|
            tr id="task-#{task.id}"
              td= link_to task.name, task
              td= task.description.truncate(30)
              td id="task-created_at" = (l task.created_at, format: :long)
              td= (l task.limit, format: :long)
              td= task.priority_i18n
              td= task.status_i18n
              td
                = link_to '編集', edit_task_path(task), class: 'btn btn-success'
                = link_to '削除', task, method: :delete, remote: true, data: {confirm: "タスク「#{task.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger delete'
    .col-md-12
      = paginate @tasks

app/views/admin/users/_user.html.slim
tr
  th scope="row" = user.id
  td= link_to user.name, admin_user_path(user)
  th= user.tasks.count
  td= user.role_i18n
  td= l user.created_at, format: :short
  td
    = link_to '編集', edit_admin_user_path(user), class: 'btn btn-success'
    = link_to '削除', admin_user_path(user), class: 'btn btn-danger', method: :delete, data: {confirm: "ユーザー「#{user.name}を削除します。よろしいですか?」"}

app/views/admin/users/edit.html.slim
.container
  .row
    .col-md-10.offset-md-1.col-lg-8.offset-lg-2
      h1.text-center ユーザー編集
      = form_with model: @user, url: admin_user_path(@user), local: true do |f|
        = render 'shared/error_messages', object: f.object
        .form-group
          = f.label :email
          = f.email_field :email, class: 'form-control'
        .form-group
          = f.label :name
          = f.text_field :name, class: 'form-control'
        .form-group
          = f.label :password
          = f.password_field :password, class: 'form-control'
        .form-group
          = f.label :role
          = f.select :role, User.roles_i18n.invert, {}, class: 'form-control'
        / html系のオプションだけ設定したい場合は、第3引数に空ハッシュを渡し、第4引数にhtml系のオプションを設定する
        = f.submit class: 'btn btn-primary'
        = link_to '戻る', admin_user_path(@user), class: 'btn btn-success'
        = link_to '削除', admin_user_path(@user), method: :delete, data: {confirm: "ユーザー「#{@user.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger delete'

app/views/admin/users/index.html.slim
.container.mb-5.pt-2
  h1 ユーザー一覧
  = link_to 'ユーザー作成', new_admin_user_path, class: 'btn btn-info'
  .row
    .col-md-12.mb-3
  / = render 'admin/users/user_search_form', search_url: admin_users_path, q: @q
  .row
    .col-md-12
      table.table.table-striped
        thead
          tr
            th scope="col" = User.human_attribute_name(:id)
            th scope="col" = User.human_attribute_name(:name)
            th scope="col" = "タスク件数"
            / #TODO: i18n化
            th scope="col" = User.human_attribute_name(:email)
            th scope="col" = User.human_attribute_name(:created_at)
            th scope="col" = User.human_attribute_name(:role)
        tbody
          = render @users
    .col-md-12.mb-3
      = paginate @users

app/views/admin/users/new.html.slim
.container
  .row
    .col-lg-8.offset-lg-2
      h1 ユーザーの新規登録
      = render 'form', user: @user

app/views/admin/users/show.html.slim
.container
  .row
    .col-md-10.offset-md-1.col-lg-8.offset-lg-2
      h1.text-center ユーザー詳細
      .text-right.mb-3
        = link_to '編集', edit_admin_user_path(@user), class: 'btn btn-success'
        = link_to '削除', admin_user_path(@user), class: 'btn btn-danger', method: :delete, data: {confirm: '削除しますか？'}
        = link_to '戻る', admin_users_path, class: 'btn btn-primary'
      table.table.table-bordered.bg-white
        tbody
          tr
            th scope="row"
              = 'id'
            td= @user.id
          tr
            th
              = '権限'
            td= @user.role_i18n
          tr
            th
              = '名前'
            td= @user.name
          tr
            th
              = 'タスク件数'
            td= @user.tasks.count
          tr
            th
              = '作成日時'
            td= l @user.created_at, format: :short
    .container.mb-5.pt-2
      .row
        .col-md-12
          = render 'shared/task_search_form', search_url: tasks_path, q: @q
        .col-md-12
          .m-3
          table.table.table-hover
            thead.thead-default
              tr
                th= Task.human_attribute_name(:name)
                th= Task.human_attribute_name(:description)
                th= sort_link(@q, :created_at, default_order: :desc)
                th= sort_link(@q, :limit)
                th= sort_link(@q, :priority)
                th= Task.human_attribute_name(:status)
            tbody
              - @tasks.each do |task|
                tr id="task-#{task.id}"
                  td= link_to task.name, task
                  td= task.description.truncate(30)
                  td id="task-created_at" = (l task.created_at, format: :long)
                  td= (l task.limit, format: :long)
                  td= task.priority_i18n
                  td= task.status_i18n
                  / TODO: ステータス、優先順位、期限、ラベルを追加し link_to 修正
                  td
                    = link_to '編集', edit_task_path(task), class: 'btn btn-success'
                    = link_to '削除', task, method: :delete, remote: true, data: {confirm: "タスク「#{task.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger delete'
        .col-md-12
          = paginate @tasks
          / # TODO: 余裕があれば、taskのindexとあわせてパーシャルにする

app/views/labels/_form.html.slim
= form_with model: label, local: true do |f|
  = render 'shared/error_messages', object: f.object
  .form-group
    = f.label Label.human_attribute_name(:name)
    = f.text_field :name, class: 'form-control', id: 'label_name'
  = f.submit nil, class: 'btn btn-primary'
  = link_to 'ラベル一覧へ戻る', labels_path, class: 'btn btn-success'

app/views/labels/edit.html.slim
.container
  .row
    .col-lg-8.offset-lg-2
      h1 ラベルの編集
      = render 'form', label: @label

app/views/labels/index.html.slim
div.row
  div.col-lg-8.offset-2
    h2 ラベル一覧
    div.text-left
      = link_to 'ラベルを作成する', new_label_path, class: 'btn btn-info', id: 'new-label-button'
    table.table.table-hover
      thead.thead-light
        tr
          th = Label.human_attribute_name(:name)
          th width='10%'
          th width='10%'
      - if @labels.exists?
        tbody
          - @labels.each do |label|
            tr
              td = label.name
              td = link_to 'ラベルを編集する', edit_label_path(label.id), class: 'btn btn-success'
              td = link_to 'ラベルを削除する', label_path(label.id), method: :delete, data: {confirm: "ラベル#{label.name}を削除しますか？"}, class: 'btn btn-danger delete'
      - else
        div = '該当するラベルはありません'
    = paginate @labels

app/views/labels/new.html.slim
.container
  .row
    .col-lg-8.offset-lg-2
      h1 ラベルの新規登録
      = render 'form', label: @label

app/views/labels/show.html.slim
h1 Labels#show
p Find me in app/views/labels/show.html.slim

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RailsSample
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand
        = link_to root_path
          = image_tag 'uuum.jpg', size: '250x68'
        - if current_user
          = render 'shared/header'
          - if current_user.admin?
            = render 'shared/admin'
          = current_user.name
        - else
          = link_to 'ログインする', login_path, class: 'btn btn-info'
    / TODO: 今回はapplicationに書いたが、本来はheaderを作りapplicationはスリムにする
    .container
    = render 'shared/flash_message'
    = yield
    = render 'shared/footer'

app/views/shared/_admin.html.slim
= link_to 'ユーザー一覧画面へ  ', admin_users_path,class: 'btn btn-success'

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_explanation
    ul
      - object.errors.full_messages.each do |msg|
        .alert.alert-danger
          li= msg

app/views/shared/_flash_message.html.slim
- flash.each do |message_type, message|
  div class=("alert alert-#{message_type}") = message

app/views/shared/_footer.html.slim
footer#footer.footer-bottom
  .container
    .row
      .col-sm-6.col-12
        .copyright
          p Copyright © 2020. UUUM_todo

app/views/shared/_header.html.slim
= link_to 'タスクを作成する  ', new_task_path, class: 'btn btn-info'
= link_to 'ラベルを作成する', new_label_path, class: 'btn btn-info'
= link_to ' ログアウト  ', logout_path, method: :delete, class: 'btn btn-danger delete'

/ = current_user.name
/ .dropdown-menu.dropdown-menu-right
  / .dropdown-item= current_user.name
  .dropdown-divider
  / = link_to t('.profile'), profiles_path, class: 'dropdown-item'
  / = link_to t('.logout'), logout_path, method: :delete, class: 'dropdown-item'

/ header#header
/   ul.navbar-nav.ml-auto.main-nav.align-items-center
/     li.nav-item
/       = link_to 'タスクを登録する', new_task_path
/     li.nav-item
/       = current_user.name
/     li.nav-item
/       = link_to 'ログアウト', logout_path, method: :delete
/         / li.nav-item.dropdown.dropdown-slide
/           / a#header-profile.nav-link aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#"
/             / = image_tag current_user.decorate.image_url, size: '25x25', class: 'rounded-circle mr15'
/             / = current_user.name
/           / .dropdown-menu.dropdown-menu-right
/           /   = link_to 'マイページ', mypages_path, class: 'dropdown-item'
            = link_to 'ログアウト', logout_path, method: :delete, class: 'dropdown-item'

app/views/shared/_task_search_form.html.slim
= search_form_for q, url: search_url do |f|
  .row
    .form-inline.align-items-center.mx-auto
      .col-auto
        - f.label :name_cont # like %name%
        = f.search_field :name_cont, class: 'form-control', placeholder: "タスク名で検索！"
      .col-auto
        - f.label :status_eq # status =
        = f.select :status_eq, Task.statuses.map { |k, v| [Task.statuses_i18n[k], v] }, {include_blank: ""}, {class: 'form-control'}
      / statusをmapで回すが、ransackがenumに対応していないので、vに 数字が渡るようにする。k はi18n
      .col-auto
        - f.label :priority_eq # priority =
        = f.select :priority_eq, Task.priorities.map { |k, v| [Task.priorities_i18n[k], v] }, {include_blank: ""}, {class: 'form-control'}
      .col-auto
        / - f.label :label_eq
        / - Label.all.each do |label|
          = f.select :labels_id_eq_any, {multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false}, label[:id]
        / = f.select :labels_id_eq_any, {multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false}, label[:id]
        / = f.select :label_eq, Label.all.map { |l| [l.name, l.id] }
        / - Label.all.each do |label|
        / = f.select :priority_eq, Label.name.map { |k, v| [Label.name[k], v] }, {include_blank: ""}, {class: 'form-control'}
        / = f.select(:label_ids,Label.all, :id, :name) do |label|
      / = f.select :label_eq, Label.map { |k, v| }
      .ml-3
        = f.submit nil, class: 'btn btn-primary'

app/views/tasks/_form.html.slim
= form_with model: task, local: true do |f|
  = render 'shared/error_messages', object: f.object
  .form-group
    = f.label Task.human_attribute_name(:name)
    = f.text_field :name, class: 'form-control', id: 'task_name'
  .form-group
    = f.label Task.human_attribute_name(:description)
    = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
  .form-group
    = f.label Task.human_attribute_name(:limit)
    = f.date_field :limit, class: 'form-control', id: 'task_limit'
  .form-group
    = f.label Task.human_attribute_name(:status)
    = f.select :status, Task.statuses_i18n.invert, {}, class: 'form-control'
  .form-group
    = f.label Task.human_attribute_name(:priority)
    = f.select :priority, Task.priorities_i18n.invert, {}, class: 'form-control'
  .form-group
    = f.collection_check_boxes(:label_ids, Label.all, :id, :name)
    / #ここでラベル全件取るのは絶対によくないと思うが、一旦実装
  = f.submit nil, class: 'btn btn-primary'
  = link_to 'タスク一覧へ戻る', root_path, class: 'btn btn-success'
  - unless task.new_record?
    = link_to '削除', task, method: :delete, remote: true, data: {confirm: "タスク「#{task.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger delete'

app/views/tasks/edit.html.slim
.container
  .row
    .col-lg-8.offset-lg-2
      h1 タスクの編集
      = render 'form', task: @task

app/views/tasks/index.html.slim
.container.mb-5.pt-2
  .row
    h2 タスク一覧
    .col-md-12
      = render 'shared/task_search_form', search_url: tasks_path, q: @q
    .col-auto
      = form_with url: tasks_path, method: :get, local: true do |f|
        / = f.label Task.human_attribute_name(:label)
        = f.select("label_id", Label.pluck(:name, :id), {include_blank: true})
        = f.submit '検索', class: 'btn btn-primary'
      .m-3
      table.table.table-hover
        thead.thead-default
          tr
            th= Task.human_attribute_name(:name)
            th= Task.human_attribute_name(:description)
            th= sort_link(@q, :created_at, default_order: :desc)
            th= sort_link(@q, :limit)
            th= sort_link(@q, :priority)
            th= Task.human_attribute_name(:status)
            th= Task.human_attribute_name(:label)
        tbody
          - @tasks.each do |task|
            tr id="task-#{task.id}"
              td= link_to task.name, task
              td= task.description.truncate(30)
              td id="task-created_at" = (l task.created_at, format: :long)
              td= (l task.limit, format: :long)
              td= task.priority_i18n
              td= task.status_i18n
              td
                - task.labels.each do |label|
                  #label.span.badge.badge-info= label.name
              td
                = link_to '編集', edit_task_path(task), class: 'btn btn-success'
                = link_to '削除', task, method: :delete, remote: true, data: {confirm: "タスク「#{task.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger delete'
    .col-md-12
      = paginate @tasks

app/views/tasks/new.html.slim
.container
  .row
    .col-lg-8.offset-lg-2
      h1 タスクの新規登録
      = render 'form', task: @task

app/views/tasks/show.html.slim
.container
  .row
    .col-lg-8.offset-lg-2
      h2 タスクの詳細
      .m-3
      .nav.justify-content-end
      table.table.table-hover
        tbody
          tr
            th= Task.human_attribute_name(:id)
            td= @task.id
          tr
            th= Task.human_attribute_name(:name)
            td= @task.name
          tr
            th= Task.human_attribute_name(:description)
            td= @task.description.truncate(30)
          tr
            th= Task.human_attribute_name(:created_at)
            td= l @task.created_at, format: :long
          tr
            th= Task.human_attribute_name(:status)
            th= @task.status_i18n
          tr
            th= Task.human_attribute_name(:priority)
            th= @task.priority_i18n
          tr
            th= Task.human_attribute_name(:label)
            th
              span.badge.badge-info
                = @task.labels.pluck(:name).join(',')
      / TODO: タスクに紐付いたラベルの名前を取り出して表示してるけどもっといい書き方あるはず
      = link_to '編集', edit_task_path, class: 'btn btn-success'
      = link_to '削除', @task, method: :delete, remote: true, data: {confirm: "タスク「#{@task.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger delete'
      = link_to 'タスク一覧へ戻る', root_path, class: 'btn btn-primary'

app/views/user_sessions/new.html.slim
.container.mb-5.pt-2
  .row
  .login-box
    .login-logo
      h1 ログイン
    .card
      .card-body.login-card-body
        = form_with scope: :session, url: login_path, local: true do |f|
          .form-group
            = f.label User.human_attribute_name(:email)
            = f.text_field :email, class: 'form-control'
          .form-group
            = f.label User.human_attribute_name(:password)
            = f.password_field :password, class: 'form-control'
          .actions
            = f.submit 'ログインする', class: 'btn btn-primary'